### ISSUE TITLE
Remove travis and add github actions

### ISSUE THREAD

**Issue by serhii73** [serhii73/place2live.com#36]
You can take config files from here https://github.com/serhii73/place2live

**Comment by TheRealChrisThomas** [comment]
First time contributing to this project. I have worked on this and I have a pull request ready. Want to make sure no one else has picked this up before I send the PR in.

**Comment by serhii73** [comment]
Thank you very much!

**Comment by NdagiStanley** [comment]
Please close this issue since it is already done.

**Comment by serhii73** [comment]
Thank you @NdagiStanley
